services:
  db:
    # Use the lightweight Alpine version of Postgres
    image: postgres:15-alpine
    container_name: daily_tracker_db
    
    # Environment variables set the DB credentials
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: health_tracker_db
    
    # Maps Port 5432 on your laptop to Port 5432 inside the container
    ports:
      - "5432:5432"
    
    # This is the "Magic" link to your SQL file
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_storage:/var/lib/postgresql/data

# This ensures your data survives if you stop the container
volumes:
  postgres_storage: